mpinet:
  encoder_layers: 18
  encoder_pretrained: true
  decoder_use_alpha: true
  num_output_channels: 2
  bins: 32

aupnet:
  bins: 32

inpnet:
  input_nc: 4
  output_nc: 3
  n_blocks: 9
  init_conv_kwargs:
    ratio_gin: 0
    ratio_gout: 0
    enable_lfu: False
  downsample_conv_kwargs:
    ratio_gin: 0
    ratio_gout: 0
    enable_lfu: False
  resnet_conv_kwargs:
    ratio_gin: 0.75
    ratio_gout: 0.75
    enable_lfu: False

renderer:
  K_max: 200
  bins: 32
